title: Elizabeth Garrison's Portfolio
logo: <img width="500" height="500" alt="e" src="https://github.com/user-attachments/assets/b198a052-774b-4bc0-a1b5-b918180950a5" />
description: Explore my past projects to grab a glimspe of me.
theme: jekyll-theme-minimal
